version: "2"
services:
  redis-master-1:
    build: ./
    ports:
      - "7002:7002"
    networks:
      redisnet:
        ipv4_address: 172.25.0.2
    command: sh -c "redis-server --port 7002 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000"
  redis-master-2:
    build: ./
    ports:
      - "7003:7003"
    networks:
      redisnet:
        ipv4_address: 172.25.0.3
    command: sh -c "redis-server --port 7003 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000"
  redis-master-3:
    build: ./
    ports:
      - "7004:7004"
    networks:
      redisnet:
        ipv4_address: 172.25.0.4
    command: sh -c "redis-server --port 7004 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000"
  redis-replica-1:
    build: ./
    ports:
      - "7005:7005"
    networks:
      redisnet:
        ipv4_address: 172.25.0.5
    command: sh -c "redis-server --port 7005 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000"
  redis-replica-2:
    build: ./
    ports:
      - "7006:7006"
    networks:
      redisnet:
        ipv4_address: 172.25.0.6
    command: sh -c "redis-server --port 7006 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000"
  redis-replica-3:
    build: ./
    ports:
      - "7007:7007"
    networks:
      redisnet:
        ipv4_address: 172.25.0.7
    command: sh -c "redis-server --port 7007 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000"

  redis-client:
    build: ./
    networks:
      redisnet:
        ipv4_address: 172.25.0.50
    command: sh -c "yes yes | redis-cli --cluster create --cluster-replicas 1 172.25.0.2:7002 172.25.0.3:7003 172.25.0.4:7004 172.25.0.5:7005 172.25.0.6:7006 172.25.0.7:7007"
    depends_on:
      - redis-master-1
      - redis-master-2
      - redis-master-3
      - redis-replica-1
      - redis-replica-2
      - redis-replica-3

  redis-server:
    build: ./
    networks:
      - redisnet
    command: sh -c "redis-server --port 7001 --cluster-config-file nodes.conf --cluster-node-timeout 5000"
    depends_on:
      - redis-client

  envoy:
    build: ./envoy
    ports:
      - "6380:6380"
      - "6381:6381"
      - "9901:9901"
    networks:
      redisnet:
        ipv4_address: 172.25.0.51
    depends_on:
    - redis-client
    - redis-server

  pumba:
    image: "gaiaadm/pumba:master"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - redisnet
    depends_on:
      - envoy

networks:
  redisnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1